//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.5.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface Person {
    PlaceHolderOrTsGenNoWorkey_FixThis: string;

    SetName(name: PersonName): void;
    GetName(): string;
}

export interface PersonInterop {
    PlaceHolderOrTsGenNoWorkey_FixThis: string;

    GetName(p: Person): string;
    SetName(p: Person, name: PersonName): void;
}

export interface PersonRepositoryInterop {
    PlaceHolderOrTsGenNoWorkey_FixThis: string;

    GetPerson1(): Person;
    GetPerson2(): Person;
}

export interface PersonRepository {
    PlaceHolderOrTsGenNoWorkey_FixThis: string;

    GetPerson1(): Person;
    GetPerson2(): Person;
}

export interface QRCode {
    Wowzers: string;

    Generate(text: string, pixelsPerBlock: number): string;
}

export interface PersonName {
    Value: string;
}

export interface Dog {
    Name: string;
    Age: number;
}

export enum Color {
    Red = 0,
    Green = 1,
    Blue = 2,
}