//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.5.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface QRCode {
    Wowzers: string;

    Generate(text: string, pixelsPerBlock: number): string;
    GetPerson(name: PersonName): Person;
    GetOwner(daggoe: Dog): Person;
}

export interface PersonName {
    Value: string;
}

export interface Dog {
    Name: string;
    Age: number;
}

export interface Person {
    Name: PersonName;
    Age: number;
    Pet: Dog;
}

export enum Color {
    Red = 0,
    Green = 1,
    Blue = 2,
}