name: Validate & Pack

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build & Validate (${{ matrix.rid }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            rid: managed
            e2e: true
            unit: true # only run unit tests once
          - os: ubuntu-24.04
            rid: linux-x64
            e2e: true
          - os: ubuntu-24.04-arm
            rid: linux-arm64
            e2e: true
          - os: ubuntu-24.04
            rid: linux-musl-x64
            e2e: false # linux-musl-x64 runners are not available on GHA
          - os: ubuntu-24.04-arm
            rid: linux-musl-arm64
            e2e: false # linux-musl-arm64 runners are not available on GHA
          - os: windows-latest
            rid: win-x64
            e2e: true 
          - os: windows-latest
            rid: win-x86
            e2e: false # win-x86 runners are not available on GHA
          - os: windows-latest
            rid: win-arm64
            e2e: false # win-arm64 runners are not available on GHA
          - os: macos-latest
            rid: osx-x64
            e2e: false # osx-x64 runners are not available on GHA
          - os: macos-latest
            rid: osx-arm64
            e2e: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-build
        with:
          rid: ${{ matrix.rid }}
      
      - name: Run Unit Tests
        if: ${{ matrix.unit }}
        continue-on-error: true
        uses: ./.github/actions/run-unit-tests
        with:
          working-directory: src
          test-target: TypeShim.slnx
          configuration: Release
          artifact-name: test-results-unit
          rid: managed

      - name: Run E2E Tests
        if: ${{ !cancelled() && matrix.e2e }}
        uses: ./.github/actions/run-e2e-tests
        with:
          working-directory: src/TypeShim.E2E/vitest
          artifact-name: test-results-e2e
          rid: ${{ matrix.rid }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pack-build-${{ matrix.rid }}
          path: src/TypeShim/bin/pack/build/${{ matrix.rid == 'managed' && '' || matrix.rid }}**
          if-no-files-found: error
          retention-days: 1

  combine:
    name: 📦 Publish Artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all RID artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: pack-build-*
          path: pack
          merge-multiple: true

      - name: Upload combined pack directory
        uses: actions/upload-artifact@v4
        with:
          name: typeshim-pack
          path: pack/**
  
  publish-results:
    name: 🧾 Publish Results
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() && !cancelled() }}
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          pattern: test-results-*
          path: results

      - name: Publish test results
        id: test-results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            results/**/*.trx
            results/**/e2e-report-*.xml

      - name: Determine badge content
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          conclusion='${{ fromJSON(steps.test-results.outputs.json).conclusion }}'
          if [ "$conclusion" = "success" ]; then
            echo "BADGE_COLOR=#26cc23" >> "$GITHUB_ENV"
            echo "BADGE_MESSAGE=${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs_succ }} passing" >> "$GITHUB_ENV"
          else
            echo "BADGE_COLOR=#cc5623" >> "$GITHUB_ENV"
            echo "BADGE_MESSAGE=${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs_fail }}/${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} failing" >> "$GITHUB_ENV"
          fi

      - name: Update badge
        if: ${{ github.event_name == 'push' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: '0f24ed28316a25f6293d5771a247f19d'
          filename: typeshim-tests-badge.json
          label: Tests
          message: ${{ env.BADGE_MESSAGE }}
          color: ${{ env.BADGE_COLOR }}

  benchmarks:
    name: 🏁 Benchmark Generator
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && !cancelled()
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: src/global.json

      - name: Build
        working-directory: src
        run: >
          dotnet build TypeShim.Benchmarks/TypeShim.Benchmarks.csproj
          --configuration Release

      - name: Build Generators
        working-directory: src/TypeShim.Benchmarks
        shell: pwsh
        run: ./Scripts/build-generators.ps1

      - name: Run Benchmarks
        working-directory: src/TypeShim.Benchmarks
        run: dotnet run --configuration Release --project TypeShim.Benchmarks.csproj --no-build

      - name: Sticky PR Benchmark Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: benchmark-results
          path: src/TypeShim.Benchmarks/BenchmarkDotNet.Artifacts/results/TypeShim.Benchmarks.GeneratorBenchmarks-report-github.md